### ISSUE TITLE
pin_project cannot be used with structs that hold mutable references

### ISSUE THREAD

**Issue by Ekleog** [taiki-e/pin-project#226] opened 2020-05-22 17:11 UTC
Hello,

I just tried using `pin-project`, as it looks like a really nice helper!

However, while doing so, I hit a wall: with `pin-project = "0.4.17"`,
```rust
#[pin_project::pin_project]
pub struct Foo<'a, R> {
    buf: &'a mut [u8],

    #[pin]
    stuff: R,
}

impl<'a, R> Foo<'a, R> {
    fn foo(self: std::pin::Pin<&mut Self>) {
        let this = self.project();
        *this.buf = &mut this.buf[1..];
    }
}

fn main() {
}
```

fails to compile with this error message:
```
   Compiling foo v0.1.0 (/tmp/foo)
error[E0495]: cannot infer an appropriate lifetime for lifetime parameter 'pin in function call due to conflicting requirements
  --> src/main.rs:11:25
   |
11 |         let this = self.project();
   |                         ^^^^^^^
   |
note: first, the lifetime cannot outlive the anonymous lifetime #1 defined on the method body at 10:5...
  --> src/main.rs:10:5
   |
10 | /     fn foo(self: std::pin::Pin<&mut Self>) {
11 | |         let this = self.project();
12 | |         *this.buf = &mut this.buf[1..];
13 | |     }
   | |_____^
note: ...but the lifetime must also be valid for the lifetime `'a` as defined on the impl at 9:6...
  --> src/main.rs:9:6
   |
9  | impl<'a, R> Foo<'a, R> {
   |      ^^
note: ...so that the types are compatible
  --> src/main.rs:11:25
   |
11 |         let this = self.project();
   |                         ^^^^^^^
   = note: expected  `std::pin::Pin<&mut Foo<'_, R>>`
              found  `std::pin::Pin<&mut Foo<'a, R>>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0495`.
error: could not compile `foo`.
```

Weirdly enough, replacing `&'a mut` by `&'a` works, so I'd guess something has been implemented specifically for `&'a` but hasn't been implemented for `&'a mut`?

Do you think it'd be possible to handle this in `pin-project`, or is it something that can't be fixed and I should just not use it? :)

**Comment by taiki-e** [comment] 2020-05-22 18:02
Hmm... I could reproduce this without pin-project ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b5d9cd57718020a3a048b64ceb6fcd8b)):

```rust
pub struct Foo<'a> {
    buf: &'a mut [u8],
}

impl<'a> Foo<'a> {
    fn foo(self: std::pin::Pin<&mut Self>) {
        self.buf = &mut self.buf[1..];
    }
}
```

I guess this related to https://github.com/rust-lang/rust/issues/54934, but I'll look into this more.

**Comment by taiki-e** [comment] 2020-05-22 18:30
Ok, this looks like https://github.com/rust-lang/rust/issues/72337 and can be fixed by adding lifetime `'a` to `std::pin::Pin<&mut Self>`:

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=37b70300fc702c32a575e445f13012de)

```diff
  impl<'a, R> Foo<'a, R> {
-     fn foo(self: std::pin::Pin<&mut Self>) {
+     fn foo(self: std::pin::Pin<&'a mut Self>) {
          let this = self.project();
          *this.buf = &mut this.buf[1..];
      }
  }
```

**Closed** 2020-05-22 18:30 UTC
Labels: C-compiler-issue, C-question

**Comment by Ekleog** [comment] 2020-05-22 18:57
Oh. You're right, this isn't related to pin-project at all, sorry for having bothered you with it!

This being said, your solution unfortunately requires the `Pin` to be borrowed for the lifetime of the whole struct, which isn't the API I'm looking for, but I'm going to raise that point with the compiler directly.

Thank you! :D

**Comment by taiki-e** [comment] 2020-05-22 19:33
I also commented on https://github.com/rust-lang/rust/issues/72477, but [this way](https://github.com/rust-lang/futures-rs/blob/71f1e054c2c85c38f28439392f1c291056051bd9/futures-util/src/io/read_exact.rs#L31-L34) should fix it completely:

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=20b19e800d86563b7213aebe166ce5d7)

```rust
#[pin_project::pin_project]
pub struct A<'a, R> {
    buf: &'a mut [u8],

    #[pin]
    stuff: R,
}

impl<'a> Foo<'a> {
    fn foo(mut self: std::pin::Pin<&mut Self>) {
        let this = self.project();
        let (_, rest) = std::mem::replace(&mut *this.buf, &mut []).split_at_mut(1);
        *this.buf = rest;
    }
}
```
